USE FuzzyKnights
GO

--	CREATE SCHEMA Query
--	GO

IF OBJECT_ID('Query.QueryMetaData') IS NOT NULL DROP TABLE Query.QueryMetaData;
IF OBJECT_ID('Query.QueryMeta') IS NOT NULL DROP TABLE Query.QueryMeta;
IF OBJECT_ID('Query.QueryMetaType') IS NOT NULL DROP TABLE Query.QueryMetaType;

IF OBJECT_ID('Query.Query') IS NOT NULL DROP TABLE Query.Query;
IF OBJECT_ID('Query.QueryType') IS NOT NULL DROP TABLE Query.QueryType;
IF OBJECT_ID('Query.DataType') IS NOT NULL DROP TABLE Query.DataType;


--	=========================================================
--		TABLES
--	=========================================================
CREATE TABLE Query.DataType (
	DataTypeID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Code VARCHAR(25) NOT NULL,
	Label VARCHAR(255) NOT NULL,
	SQLDataType VARCHAR(255) NOT NULL,
	
	UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),

	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	ModifiedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	DeactivatedDateTimeUTC DATETIME2(3) NULL
);
INSERT INTO Query.DataType (Code, Label, SQLDataType)
VALUES
	('STR', 'String', 'VARCHAR'),
	('INT', 'Integer', 'INT'),
	('BOOL', 'Boolean', 'BIT'),
	('NUM', 'Number', 'NUMERIC');

CREATE TABLE Query.QueryType (
	QueryTypeID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Code VARCHAR(25) NOT NULL,
	Label VARCHAR(255) NOT NULL,

	UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),

	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	ModifiedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	DeactivatedDateTimeUTC DATETIME2(3) NULL
);
INSERT INTO Query.QueryType (Code, Label)
VALUES
	('SELECT', 'Select'),
	('INSERT', 'Insert'),
	('UPDATE', 'Update'),
	('DELETE', 'Delete'),
	('SPROC', 'Stored Procedure'),
	('TVF', 'Table-Valued Function');

CREATE TABLE Query.Query (
	QueryID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	QueryTypeID INT NOT NULL FOREIGN KEY REFERENCES Query.QueryType (QueryTypeID),
	Name VARCHAR(255) NOT NULL,
	Query NVARCHAR(MAX) NOT NULL,

	UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),

	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	ModifiedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	DeactivatedDateTimeUTC DATETIME2(3) NULL
);


CREATE TABLE Query.QueryMetaType (
	QueryMetaTypeID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Code VARCHAR(25) NOT NULL,
	Label VARCHAR(255) NOT NULL,

	UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),

	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	ModifiedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	DeactivatedDateTimeUTC DATETIME2(3) NULL
);
INSERT INTO Query.QueryMetaType (Code, Label)
VALUES
	('RESULT_SET', 'Result Set'),
	('PARAMS', 'Parameters');

CREATE TABLE Query.QueryMeta (
	QueryMetaID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	QueryID INT NOT NULL FOREIGN KEY REFERENCES Query.Query (QueryID),
	QueryMetaTypeID INT NOT NULL FOREIGN KEY REFERENCES Query.QueryMetaType (QueryMetaTypeID),

	UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),

	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	ModifiedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	DeactivatedDateTimeUTC DATETIME2(3) NULL
);

CREATE TABLE Query.QueryMetaData (
	QueryMetaDataID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	QueryMetaID INT NOT NULL FOREIGN KEY REFERENCES Query.QueryMeta (QueryMetaID),
	DataTypeID INT NOT NULL FOREIGN KEY REFERENCES Query.DataType (DataTypeID),
	DataTypePrecision VARCHAR(255) NULL,
	Code VARCHAR(25) NOT NULL,
	Label VARCHAR(255) NOT NULL,

	UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),

	CreatedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	ModifiedDateTimeUTC DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	DeactivatedDateTimeUTC DATETIME2(3) NULL
);